import type { ProductPricingModel } from '@/services/types';

export interface SeedProductCatalogItem {
  id: string;
  name: string;
  category: string;
  description: string;
  aliases: string[];
  pricingModel: ProductPricingModel;
  monthlyPriceLow: number;
  monthlyPriceHigh: number;
}

export const PRODUCT_CATALOG: SeedProductCatalogItem[] = [
  {
    id: 'product-core-package',
    name: 'Core Package',
    category: 'Managed Services',
    description: 'Managed endpoint security, operating-system patching, asset tracking, device monitoring, disk health, privileged access, and pay-as-you-go help desk access.',
    aliases: [
      'Core Package - PC', 'Core Package - Mac', 'Core Package - Per User', 'Core Package - BYOD',
      'PC Core Package', 'Mac Core Package', 'CorePkgMacNonProfit', 'CorePkgPCNonProfit',
      'CorePkgiPadPomeroy', 'CorePkgWorkstations.SW', 'CorePkgRightworks.SW', 'CorePkgPCJA.eng',
      'CorePkgPCJA.in.wrkstn', 'CorePkgPCJA.ua.lv', 'CorePkgPCJA.ua.uz', 'CorePkgPCJA.us',
    ],
    pricingModel: 'per-device',
    monthlyPriceLow: 9,
    monthlyPriceHigh: 91,
  },
  {
    id: 'product-unlimited-support',
    name: 'Unlimited Support Package',
    category: 'Managed Services',
    description: 'Core endpoint management plus unlimited Tier 1 and Tier 2 remote support during business hours.',
    aliases: [
      'Unlimited Support Package - PC', 'Unlimited Support Package - Mac',
      'Unlimited Support PC Package', 'Unlimited Support Mac Package',
      'UnlimitedSupportPkgPCNP', 'UnlimitedSupportPkgMacNP',
    ],
    pricingModel: 'per-device',
    monthlyPriceLow: 27,
    monthlyPriceHigh: 108,
  },
  {
    id: 'product-premium-unlimited-support',
    name: 'Premium Unlimited Support Package',
    category: 'Managed Services',
    description: 'Core endpoint management plus unlimited Tier 1, Tier 2, and Tier 3 support, quarterly business and security assessments, and the NIST Security Pack.',
    aliases: ['Prem Unlimited Support PC Pkg', 'Prem Unlimited Support Mac Pkg', 'Premium Support Package'],
    pricingModel: 'per-device',
    monthlyPriceLow: 146,
    monthlyPriceHigh: 146,
  },
  {
    id: 'product-security-awareness',
    name: 'Security Awareness Training',
    category: 'Security',
    description: 'Managed phishing simulations, reporting, and recurring security awareness training via KnowBe4.',
    aliases: ['Security Awareness Package', 'Security Awareness & Training Package via KnowBe4', 'SAT', 'phishing training', 'security training'],
    pricingModel: 'per-user',
    monthlyPriceLow: 3,
    monthlyPriceHigh: 19,
  },
  {
    id: 'product-itdr',
    name: 'Identity Threat Detection & Response',
    category: 'Security',
    description: 'Managed identity threat detection and response with 24/7 security operations monitoring.',
    aliases: ['Managed ITDR', 'ITDR', 'ITDR a la carte', 'identity threat detection'],
    pricingModel: 'per-user',
    monthlyPriceLow: 4,
    monthlyPriceHigh: 13,
  },
  {
    id: 'product-email-security',
    name: 'Advanced Email Security',
    category: 'Security',
    description: 'Advanced email and collaboration protection against phishing, impersonation, spam, and malicious content.',
    aliases: ['Enterprise Email Protection', 'Managed SPAM Filtering', 'Reflexion Spam Filter', 'email security', 'anti-phishing', 'spam filtering'],
    pricingModel: 'per-user',
    monthlyPriceLow: 3,
    monthlyPriceHigh: 8,
  },
  {
    id: 'product-dns-protection',
    name: 'DNS Protection',
    category: 'Security',
    description: 'Cloud-delivered DNS security against malware, botnets, and phishing for managed users and networks.',
    aliases: ['Open DNS Protection', 'DNS Protection Agent', 'DNS Protection Network', 'OpenDNS'],
    pricingModel: 'per-user',
    monthlyPriceLow: 3,
    monthlyPriceHigh: 4,
  },
  {
    id: 'product-breach-monitoring',
    name: 'Breach Monitoring',
    category: 'Security',
    description: 'Ongoing monitoring of company user accounts for known and potential credential breaches.',
    aliases: ['Pwd/Acct Breach Detector (P1)', 'Pwd/Acct Breach Detector (P2)', 'Breach Monitoring via HIBP', 'HIBP'],
    pricingModel: 'flat',
    monthlyPriceLow: 50,
    monthlyPriceHigh: 106,
  },
  {
    id: 'product-mfa',
    name: 'Multi-Factor Authentication',
    category: 'Security',
    description: 'Managed Duo multi-factor authentication for stronger protection of user identities and applications.',
    aliases: ['Duo 2FA', 'Duo MFA', 'MFA', '2FA', 'multi-factor authentication'],
    pricingModel: 'per-user',
    monthlyPriceLow: 3,
    monthlyPriceHigh: 4,
  },
  {
    id: 'product-managed-antivirus',
    name: 'Managed Antivirus',
    category: 'Security',
    description: 'Managed antivirus protection, monitoring, and policy administration for endpoints.',
    aliases: ['Managed Antivirus a la carte', 'Managed Antivirus Protection', 'antivirus', 'endpoint protection'],
    pricingModel: 'per-device',
    monthlyPriceLow: 3,
    monthlyPriceHigh: 7,
  },
  {
    id: 'product-managed-siem',
    name: 'Managed SIEM',
    category: 'Security',
    description: 'Managed security information and event monitoring, detection, and response via Huntress.',
    aliases: ['Huntress Security Information and Event Management', 'Managed SOC', 'MDR', 'SOC', 'SIEM'],
    pricingModel: 'flat',
    monthlyPriceLow: 75,
    monthlyPriceHigh: 200,
  },
  {
    id: 'product-vulnerability-management',
    name: 'Vulnerability Management',
    category: 'Security',
    description: 'Continuous vulnerability management and compliance monitoring via ConnectSecure.',
    aliases: ['ConnectSecure', 'Vulnerability Mgmt + Comp', 'vulnerability management', 'continuous vulnerability scanning'],
    pricingModel: 'per-user',
    monthlyPriceLow: 4,
    monthlyPriceHigh: 6,
  },
  {
    id: 'product-vulnerability-assessment',
    name: 'Vulnerability Assessment',
    category: 'Security',
    description: 'Scheduled internal vulnerability scanning with findings that support remediation and risk reduction.',
    aliases: ['Security - Vulnerability Scan', 'vulnerability scan', 'vulnerability assessment', 'risk scan'],
    pricingModel: 'flat',
    monthlyPriceLow: 53,
    monthlyPriceHigh: 212,
  },
  {
    id: 'product-password-manager',
    name: 'Enterprise Password Manager',
    category: 'Security',
    description: 'Managed enterprise password security, sharing, single sign-on integration, and policy enforcement via Bitwarden.',
    aliases: ['Security policy via BitWarden', 'Bitwarden', 'password manager'],
    pricingModel: 'per-user',
    monthlyPriceLow: 7,
    monthlyPriceHigh: 7,
  },
  {
    id: 'product-secure-remote-access',
    name: 'Secure Remote Access / VPN',
    category: 'Security',
    description: 'Zero Trust remote access to company resources for remote and hybrid users via Twingate.',
    aliases: ['Remote VPN', 'VPN - Twingate', 'Twingate', 'zero trust network access', 'ZTNA'],
    pricingModel: 'per-user',
    monthlyPriceLow: 7,
    monthlyPriceHigh: 7,
  },
  {
    id: 'product-m365-cloud-backup',
    name: 'Microsoft 365 Cloud Backup',
    category: 'Backup',
    description: 'Automatic backup and recovery for Microsoft 365 email, calendars, OneDrive, SharePoint, and Teams.',
    aliases: ['Backup - Spanning O365', 'Spanning O365 Cloud Backup', 'Microsoft 365 Backup', 'M365 backup', 'Office 365 backup'],
    pricingModel: 'per-user',
    monthlyPriceLow: 3,
    monthlyPriceHigh: 7,
  },
  {
    id: 'product-google-cloud-backup',
    name: 'Google Workspace Cloud Backup',
    category: 'Backup',
    description: 'Backup and rapid recovery for Gmail, Drive, shared drives, calendars, contacts, and Sites.',
    aliases: ['Backup - Spanning Google', 'Spanning Google Cloud Backup', 'Google Workspace backup', 'Google cloud backup'],
    pricingModel: 'per-user',
    monthlyPriceLow: 2,
    monthlyPriceHigh: 6,
  },
  {
    id: 'product-salesforce-cloud-backup',
    name: 'Salesforce Cloud Backup',
    category: 'Backup',
    description: 'Independent cloud backup and recovery for Salesforce business data.',
    aliases: ['Backup - Spanning Salesforce', 'Spanning Salesforce', 'Salesforce backup'],
    pricingModel: 'per-user',
    monthlyPriceLow: 4,
    monthlyPriceHigh: 5,
  },
  {
    id: 'product-workstation-cloud-backup',
    name: 'Workstation Cloud Backup',
    category: 'Backup',
    description: 'Managed cloud backup for workstation business data via Ninja Data Protection.',
    aliases: ['Backup - Managed Workstation', 'Cloud Backup for Workstations', 'Ninja Data Protection', 'workstation backup'],
    pricingModel: 'per-device',
    monthlyPriceLow: 9,
    monthlyPriceHigh: 27,
  },
  {
    id: 'product-managed-server-backup',
    name: 'Managed Server Backup / BCDR',
    category: 'Backup',
    description: 'Managed server and file backup with off-site replication and recovery options across supported backup platforms.',
    aliases: [
      'Backup - Managed Server (P1)', 'Backup - Managed Server (P2)', 'Backup - Managed Server',
      'Unitrends server backups', 'Cloud Backup for Servers via NinjaOne', 'Generic Cloud Backup for Servers',
      'Managed Backup & Disaster Recovery', 'BCDR', 'business continuity', 'disaster recovery',
    ],
    pricingModel: 'flat',
    monthlyPriceLow: 32,
    monthlyPriceHigh: 618,
  },
  {
    id: 'product-network-monitoring',
    name: 'Network Monitoring',
    category: 'Infrastructure',
    description: 'Managed network-level protection, availability monitoring, and equipment monitoring.',
    aliases: ['Monitoring - Network', 'network monitoring', 'network equipment monitoring'],
    pricingModel: 'flat',
    monthlyPriceLow: 265,
    monthlyPriceHigh: 618,
  },
  {
    id: 'product-isp-monitoring',
    name: 'ISP Monitoring',
    category: 'Infrastructure',
    description: 'Managed monitoring of internet service availability and connectivity at a client site.',
    aliases: ['Monitoring - ISP', 'internet monitoring', 'internet service monitoring'],
    pricingModel: 'flat',
    monthlyPriceLow: 85,
    monthlyPriceHigh: 212,
  },
  {
    id: 'product-managed-firewall',
    name: 'Managed Firewall',
    category: 'Infrastructure',
    description: 'Fully managed firewall protection, configuration, and monitoring for a client network.',
    aliases: ['Managed Firewall', 'Fully Managed Cisco Firewall', 'Cisco managed firewall', 'firewall management'],
    pricingModel: 'flat',
    monthlyPriceLow: 68,
    monthlyPriceHigh: 204,
  },
  {
    id: 'product-private-cloud-hosting',
    name: 'Private Cloud Hosting',
    category: 'Hosting',
    description: 'Managed private cloud hosting and dedicated hosted cloud instances.',
    aliases: ['Hosting - Private Cloud', 'Hosting - Private Cloud Inst.', 'Private Cloud Instance', 'private cloud'],
    pricingModel: 'flat',
    monthlyPriceLow: 146,
    monthlyPriceHigh: 442,
  },
  {
    id: 'product-pci-dss-compliance',
    name: 'PCI DSS Compliance Service',
    category: 'Compliance',
    description: 'Quarterly PCI vulnerability scans and assistance with the SAQ A self-assessment questionnaire.',
    aliases: ['PCIDSS Service w/ SAQ A', 'PCI DSS', 'PCI compliance', 'SAQ A'],
    pricingModel: 'flat',
    monthlyPriceLow: 920,
    monthlyPriceHigh: 975,
  },
];
